[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[OUTPUT]
    Name            es
    Match           *
    Host            elasticsearch
    Port            9200
    Index           spring-logs
    Type            _doc
    Suppress_Type_Name On
    # Security disable only local
    HTTP_User       elastic
    HTTP_Passwd     changeme
    tls             Off