INSERT INTO users (username, email) VALUES ('user01', 'user01@mail.com');
INSERT INTO users (username, email) VALUES ('user02', 'user02@mail.com');
INSERT INTO users (username, email) VALUES ('user03', 'user03@mail.com');
INSERT INTO users (username, email) VALUES ('user04', 'user04@mail.com');
INSERT INTO users (username, email) VALUES ('user05', 'user05@mail.com');
INSERT INTO users (username, email) VALUES ('user06', 'user06@mail.com');
INSERT INTO users (username, email) VALUES ('user07', 'user07@mail.com');
INSERT INTO users (username, email) VALUES ('user08', 'user08@mail.com');
INSERT INTO users (username, email) VALUES ('user09', 'user09@mail.com');
INSERT INTO users (username, email) VALUES ('user10', 'user10@mail.com');

INSERT INTO users (username, email) VALUES ('user11', 'user11@mail.com');
INSERT INTO users (username, email) VALUES ('user12', 'user12@mail.com');
INSERT INTO users (username, email) VALUES ('user13', 'user13@mail.com');
INSERT INTO users (username, email) VALUES ('user14', 'user14@mail.com');
INSERT INTO users (username, email) VALUES ('user15', 'user15@mail.com');
INSERT INTO users (username, email) VALUES ('user16', 'user16@mail.com');
INSERT INTO users (username, email) VALUES ('user17', 'user17@mail.com');
INSERT INTO users (username, email) VALUES ('user18', 'user18@mail.com');
INSERT INTO users (username, email) VALUES ('user19', 'user19@mail.com');
INSERT INTO users (username, email) VALUES ('user20', 'user20@mail.com');

INSERT INTO users (username, email) VALUES ('user21', 'user21@mail.com');
INSERT INTO users (username, email) VALUES ('user22', 'user22@mail.com');
INSERT INTO users (username, email) VALUES ('user23', 'user23@mail.com');
INSERT INTO users (username, email) VALUES ('user24', 'user24@mail.com');
INSERT INTO users (username, email) VALUES ('user25', 'user25@mail.com');
INSERT INTO users (username, email) VALUES ('user26', 'user26@mail.com');
INSERT INTO users (username, email) VALUES ('user27', 'user27@mail.com');
INSERT INTO users (username, email) VALUES ('user28', 'user28@mail.com');
INSERT INTO users (username, email) VALUES ('user29', 'user29@mail.com');
INSERT INTO users (username, email) VALUES ('user30', 'user30@mail.com');

INSERT INTO users (username, email) VALUES ('user31', 'user31@mail.com');
INSERT INTO users (username, email) VALUES ('user32', 'user32@mail.com');
INSERT INTO users (username, email) VALUES ('user33', 'user33@mail.com');
INSERT INTO users (username, email) VALUES ('user34', 'user34@mail.com');
INSERT INTO users (username, email) VALUES ('user35', 'user35@mail.com');
INSERT INTO users (username, email) VALUES ('user36', 'user36@mail.com');
INSERT INTO users (username, email) VALUES ('user37', 'user37@mail.com');
INSERT INTO users (username, email) VALUES ('user38', 'user38@mail.com');
INSERT INTO users (username, email) VALUES ('user39', 'user39@mail.com');
INSERT INTO users (username, email) VALUES ('user40', 'user40@mail.com');

INSERT INTO users (username, email) VALUES ('user41', 'user41@mail.com');
INSERT INTO users (username, email) VALUES ('user42', 'user42@mail.com');
INSERT INTO users (username, email) VALUES ('user43', 'user43@mail.com');
INSERT INTO users (username, email) VALUES ('user44', 'user44@mail.com');
INSERT INTO users (username, email) VALUES ('user45', 'user45@mail.com');
INSERT INTO users (username, email) VALUES ('user46', 'user46@mail.com');
INSERT INTO users (username, email) VALUES ('user47', 'user47@mail.com');
INSERT INTO users (username, email) VALUES ('user48', 'user48@mail.com');
INSERT INTO users (username, email) VALUES ('user49', 'user49@mail.com');
INSERT INTO users (username, email) VALUES ('user50', 'user50@mail.com');

INSERT INTO users (username, email) VALUES ('user51', 'user51@mail.com');
INSERT INTO users (username, email) VALUES ('user52', 'user52@mail.com');
INSERT INTO users (username, email) VALUES ('user53', 'user53@mail.com');
INSERT INTO users (username, email) VALUES ('user54', 'user54@mail.com');
INSERT INTO users (username, email) VALUES ('user55', 'user55@mail.com');
INSERT INTO users (username, email) VALUES ('user56', 'user56@mail.com');
INSERT INTO users (username, email) VALUES ('user57', 'user57@mail.com');
INSERT INTO users (username, email) VALUES ('user58', 'user58@mail.com');
INSERT INTO users (username, email) VALUES ('user59', 'user59@mail.com');
INSERT INTO users (username, email) VALUES ('user60', 'user60@mail.com');

INSERT INTO users (username, email) VALUES ('user61', 'user61@mail.com');
INSERT INTO users (username, email) VALUES ('user62', 'user62@mail.com');
INSERT INTO users (username, email) VALUES ('user63', 'user63@mail.com');
INSERT INTO users (username, email) VALUES ('user64', 'user64@mail.com');
INSERT INTO users (username, email) VALUES ('user65', 'user65@mail.com');
INSERT INTO users (username, email) VALUES ('user66', 'user66@mail.com');
INSERT INTO users (username, email) VALUES ('user67', 'user67@mail.com');
INSERT INTO users (username, email) VALUES ('user68', 'user68@mail.com');
INSERT INTO users (username, email) VALUES ('user69', 'user69@mail.com');
INSERT INTO users (username, email) VALUES ('user70', 'user70@mail.com');

INSERT INTO users (username, email) VALUES ('user71', 'user71@mail.com');
INSERT INTO users (username, email) VALUES ('user72', 'user72@mail.com');
INSERT INTO users (username, email) VALUES ('user73', 'user73@mail.com');
INSERT INTO users (username, email) VALUES ('user74', 'user74@mail.com');
INSERT INTO users (username, email) VALUES ('user75', 'user75@mail.com');
INSERT INTO users (username, email) VALUES ('user76', 'user76@mail.com');
INSERT INTO users (username, email) VALUES ('user77', 'user77@mail.com');
INSERT INTO users (username, email) VALUES ('user78', 'user78@mail.com');
INSERT INTO users (username, email) VALUES ('user79', 'user79@mail.com');
INSERT INTO users (username, email) VALUES ('user80', 'user80@mail.com');

INSERT INTO users (username, email) VALUES ('user81', 'user81@mail.com');
INSERT INTO users (username, email) VALUES ('user82', 'user82@mail.com');
INSERT INTO users (username, email) VALUES ('user83', 'user83@mail.com');
INSERT INTO users (username, email) VALUES ('user84', 'user84@mail.com');
INSERT INTO users (username, email) VALUES ('user85', 'user85@mail.com');
INSERT INTO users (username, email) VALUES ('user86', 'user86@mail.com');
INSERT INTO users (username, email) VALUES ('user87', 'user87@mail.com');
INSERT INTO users (username, email) VALUES ('user88', 'user88@mail.com');
INSERT INTO users (username, email) VALUES ('user89', 'user89@mail.com');
INSERT INTO users (username, email) VALUES ('user90', 'user90@mail.com');

INSERT INTO users (username, email) VALUES ('user91', 'user91@mail.com');
INSERT INTO users (username, email) VALUES ('user92', 'user92@mail.com');
INSERT INTO users (username, email) VALUES ('user93', 'user93@mail.com');
INSERT INTO users (username, email) VALUES ('user94', 'user94@mail.com');
INSERT INTO users (username, email) VALUES ('user95', 'user95@mail.com');
INSERT INTO users (username, email) VALUES ('user96', 'user96@mail.com');
INSERT INTO users (username, email) VALUES ('user97', 'user97@mail.com');
INSERT INTO users (username, email) VALUES ('user98', 'user98@mail.com');
INSERT INTO users (username, email) VALUES ('user99', 'user99@mail.com');
INSERT INTO users (username, email) VALUES ('user100', 'user100@mail.com');


INSERT INTO users (username, email) VALUES ('auser100', 'euser100@mail.com');
INSERT INTO users (username, email) VALUES ('buser100', 'fuser100@mail.com');
INSERT INTO users (username, email) VALUES ('cuser100', 'fuser100@mail.com');
INSERT INTO users (username, email) VALUES ('duser100', 'euser100@mail.com');
INSERT INTO users (username, email) VALUES ('efqwfguser100', 'guser100@mail.com');
INSERT INTO users (username, email) VALUES ('usfergger100', 'ureqser100@mail.com');
INSERT INTO users (username, email) VALUES ('ferusegr100', 'user10rgh0@mrail.com');
INSERT INTO users (username, email) VALUES ('usgger100', 'userg100@mrail.com');